# - name: update packages
  #  apt: update_cache=yes

- name: install packages
  sudo: yes
  apt: 
    name:
      - python3
      - git
      - python3-pip
      - python
      - python-pip
    state: present

  