---
# - name: update packages
  #  apt: update_cache=yes

- lineinfile:
    path: /etc/environment
    line: 'http_proxy="http://wwwproxy.unimelb.edu.au:8000"'
    create: yes

- lineinfile:
    path: /etc/environment
    line: 'https_proxy="http://wwwproxy.unimelb.edu.au:8000"'
    create: yes

- lineinfile:
    path: /etc/environment
    line: 'ftp_proxy="http://wwwproxy.unimelb.edu.au:8000"'
    create: yes

- name: install packages
  sudo: yes
  apt: 
    name:
      - python3
      - git
      - python3-pip
      - python
      - python-pip
    state: present
  