---
# Create an instance for webServer on NecTAR
- name: Create an instance for webServer
  os_server:
    name: webServer
    image: '{{ instance_image }}'
    key_name: webServer
    flavor: '{{ instance_flavor }}'
    network: '{{ instance_network }}'
    availability_zone: '{{ availability_zone }}'
    security_groups: '{{ sg_names }}'
    volumes: webServer
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  register: os_instance_webServer

- debug:
    msg: "instance webServer has been created. IP address is {{ os_instance_webServer.openstack.public_v4 }}"
  when: os_instance_webServer.openstack is defined

- name: Print the ip address to inventory
  shell: echo "[webServer]\n{{ os_instance_webServer.openstack.public_v4 }} ansible_ssh_private_key_file=./keys/webServer.key\n" >> ../Config/inventory/hosts.ini

- lineinfile:
    path: ../Config/var/var.yml
    line: 'webServer: {{ os_instance_webServer.openstack.public_v4 }}'
    create: yes