---
# Create an instance for harvester2 on NecTAR
- name: Create an instance for harvester2
  os_server:
    name: harvester2
    image: '{{ instance_image }}'
    key_name: harvester2
    flavor: '{{ instance_flavor }}'
    network: '{{ instance_network }}'
    availability_zone: '{{ availability_zone }}'
    security_groups: '{{ sg_names }}'
    volumes: harvester2
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  register: os_instance_harvester2

- debug:
    msg: "instance harvester2 has been created. IP address is {{ os_instance_harvester2.openstack.public_v4 }}"
  when: os_instance_harvester2.openstack is defined

- name: Print the ip address to inventory
  shell: echo "[harvester2]\n{{ os_instance_harvester2.openstack.public_v4 }} ansible_ssh_private_key_file=./keys/harvester2.key\n" >> ../Config/inventory/hosts.ini

- lineinfile:
    path: ../Config/var/var.yml
    line: 'harvester2: {{ os_instance_harvester2.openstack.public_v4 }}'
    create: yes