# Common vars
availability_zone: melbourne-qh2-uom

# Volume
volumes:
  - vol_name: demo-vol-1
    vol_size: 10

# Security group
security_groups:
  - name: demo_ssh
    description: "Demo security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0

# Instance
instance_name: web_server
instance_image: 0a2bac09-8beb-464a-9cbc-6adf4dfcd5e5
instance_key_name: CCC-key
instance_flavor: m1.small