# Configure couchdb in main database
- name: Install couchdb container
  sudo: yes
  docker_container:
    name: couchdb
    image: "couchdb:2.3.0"
    ports: 
      - "5984:5984"
      - "4369:4369"
      - "9100:9100"
      - "9200:9200"
    env:
      COUCHDB_USER: "admin"
      COUCHDB_PASSWORD: "admin"
      NODENAME: '{{ dbServer }}'

- name: Copy sh script to server
  copy: 
    src: cluster.sh 
    dest: /etc/cluster.sh

- name: chmod
  shell: chmod 755 /etc/cluster.sh

- name: Copy curl command into shell script - harvester1
  lineinfile: 
    path: /etc/cluster.sh
    line: 'curl -X POST -H "Content-Type: application/json" http://admin:admin@127.0.0.1:5984/_cluster_setup -d ''{"action": "add_node", "host": "{{ harvester1 }}", "port": "5984", "username": "admin", "password":"admin"}'''

- name: Copy curl command into shell script - harvester2
  lineinfile: 
    path: /etc/cluster.sh
    line: 'curl -X POST -H "Content-Type: application/json" http://admin:admin@127.0.0.1:5984/_cluster_setup -d ''{"action": "add_node", "host": "{{ harvester2 }}", "port": "5984", "username": "admin", "password":"admin"}'''

- name: Copy curl command into shell script - finish
  lineinfile:
    path: /etc/cluster.sh
    line: 'curl -X POST -H "Content-Type: application/json" http://admin:admin@127.0.0.1:5984/_cluster_setup -d ''{"action": "finish_cluster"}'''

- shell: sudo sleep 60

- name: Run the script
  shell: /etc/cluster.sh 


