# Configure couchdb in main database
- name: Install couchdb container
  sudo: yes
  docker_container:
    name: couchdb
    image: "couchdb:2.3.0"
    ports: 
      - "5984:5984"
      - "4369:4369"
      - "9100:9100"
      - "9200:9200"
    env:
      COUCHDB_USER: "admin"
      COUCHDB_PASSWORD: "admin"
      NODENAME: '{{ dbServer }}'

- name: enable the cluster
  uri: status_code=201 HEADER_Content-Type="application/json" user=admin password=admin method=POST body_format=json url=http://127.0.0.1:5984/_cluster_setup body='{"action":"enable_cluster","bind_address":"0.0.0.0","username":"admin","password":"admin","node_count":"{{ COUNT_NODES }}"}'


- name: add nodes to the cluster
  uri: status_code=201,409 HEADER_Content-Type="application/json" user=admin password=admin method=POST force_basic_auth=yes body_format=json url=http://127.0.0.1:5984/_cluster_setup body='{"action":"add_node","username":"admin","password":"admin","host":"{{ item }}","port":5984}'
  with_items: 
    - '{{ harvester1 }}'
    - '{{ harvester2 }}'


- name: finish the cluster
  uri: status_code=201 HEADER_Content-Type="application/json" user=admin password=admin method=POST force_basic_auth=yes url=http://127.0.0.1:5984/_cluster_setup body_format=json body='{"action":"finish_cluster"}'