- name: Install couchdb container
  sudo: yes
  docker_container:
    name: couchdb
    image: "couchdb:2.3.0"
    ports: 
      - "5984:5984"
    env:
      COUCHDB_USER: "admin"
      COUCHDB_PASSWORD: "admin"
      NODENAME: '{{ dbserver }}'