---
# Create an instance for harvester1 on NecTAR
- name: Create an instance for harvester1
  os_server:
    name: harvester1
    image: '{{ instance_image }}'
    key_name: harvester1
    flavor: '{{ instance_flavor }}'
    network: '{{ instance_network }}'
    availability_zone: '{{ availability_zone }}'
    security_groups: '{{ sg_names }}'
    volumes: harvester1
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  register: os_instance

- debug:
    msg: "instance harvester1 has been created. IP address is {{ os_instance.openstack.public_v4 }}"
  when: os_instance.openstack is defined

- name: Print the ip address to inventory
  shell: echo "[harvester1]\n{{ os_instance.openstack.public_v4 }} ansible_ssh_private_key_file=./keys/harvester1.key\n" >> ../Config/inventory/hosts.ini

- lineinfile:
    path: ../Config/var/var.yml
    line: 'harvester1: {{ os_instance.openstack.public_v4 }}'
    create: yes