---
# docker configuration

- name: Add Docker’s official GPG key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
    | sudo apt-key add -

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
    state: present
    filename: docker

- name: Install misc packages
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - "aptitude"
    - "apt-transport-https"
    - "ca-certificates"
    - "curl"
    - "software-properties-common"

- name: Install 'docker-ce'
  apt:
    name: "docker-ce"
    update_cache: yes

- name: Update pip
  pip:
    name: pip
    extra_args: --upgrade
    executable: pip3 


- name: Pip docker 
  pip:
    name: 
      - docker
    # executable: pip3

- name: Move storage path 
  shell: mv -f /var/lib/docker /data

- name: Link storage
  shell: ln -s /data/docker /var/lib/docker


- name: Create proxy files
  shell: mkdir -p /etc/systemd/system/docker.service.d

- name: Create http-proxy
  command: sudo touch /etc/systemd/system/docker.service.d/http-proxy.conf

- name: Create https-proxy
  command: sudo touch /etc/systemd/system/docker.service.d/https-proxy.conf

- name: Create ftp-proxy
  command: sudo touch /etc/systemd/system/docker.service.d/ftp-proxy.conf

- name: Create no-proxy
  command: sudo touch /etc/systemd/system/docker.service.d/no-proxy.conf

- name: Set http-proxy
  copy: src=./roles/docker/configs/http-proxy.conf dest=/etc/systemd/system/docker.service.d/http-proxy.conf

- name: Set https-proxy
  copy: src=./roles/docker/configs/https-proxy.conf dest=/etc/systemd/system/docker.service.d/https-proxy.conf

- name: Set ftp-proxy
  copy: src=./roles/docker/configs/ftp-proxy.conf dest=/etc/systemd/system/docker.service.d/ftp-proxy.conf

- name: Set no-proxy
  copy: src=./roles/docker/configs/no-proxy.conf dest=/etc/systemd/system/docker.service.d/no-proxy.conf


- name: Restart daemon-reload
  command: sudo systemctl daemon-reload

- name: Restart docker
  command: sudo systemctl restart docker




